version: '2'

services:
  teensyduino-base:
    build:
      context: .
      dockerfile: Dockerfile.teensyduino
    image: teensyduino-base:latest
    container_name: teensyduino-base

  midi-to-hid:
    build:
      context: .
      dockerfile: Dockerfile
    image: teensy-midi-to-hid:latest
    container_name: midi-to-hid
    depends_on:
      - teensyduino-base
    volumes:
        - .:/srv
    stdin_open: true
    tty: true

